{
    "defBtnFocus": {
        "wType": "Button",
        "bg_type": "one",
        "border_color": "ffffff00",
        "border_style": "plain",
        "border_width": 0,
        "border_type": 0,
        "font_color": "ffffff00",
        "font_name": "Helvetica",
        "font_size": 150,
        "font_style": "normal",
        "font_weight": "400",
        "background_color": "6fa0f400"
    },
    "defBtnNormal": {
        "wType": "Button",
        "bg_type": "one",
        "border_color": "ffffff00",
        "border_style": "plain",
        "border_width": 0,
        "border_type": 0,
        "font_color": "ffffff00",
        "font_name": "Helvetica",
        "font_size": 150,
        "font_style": "normal",
        "font_weight": "400",
        "background_color": "4b88f100"
    },
    "defLabel": {
        "wType": "Label",
        "bg_type": "one",
        "border_color": "42424200",
        "border_style": "plain",
        "border_width": 0,
        "border_type": 0,
        "font_color": "33333300",
        "font_name": "Helvetica",
        "font_size": 200,
        "font_style": "normal",
        "font_weight": "400",
        "background_color": "00000064"
    },
    "sknLblDescription": {
        "wType": "Label",
        "bg_type": "one",
        "border_color": "42424200",
        "border_style": "plain",
        "border_width": 0,
        "border_type": 0,
        "font_color": "57575700",
        "font_name": "Helvetica",
        "font_size": 92,
        "font_style": "normal",
        "font_weight": "normal",
        "background_color": "00000064",
        "forked": false
    },
    "sknLblRowHeading": {
        "wType": "Label",
        "bg_type": "one",
        "border_type": 0,
        "font_color": "00000000",
        "font_name": "Helvetica",
        "font_size": 107,
        "font_style": "normal",
        "font_weight": "bold",
        "background_color": "00000064",
        "shadow": {
            "br": 0,
            "color": "00000000",
            "inner": false,
            "nm": 0,
            "x": 0,
            "y": 0
        },
        "text_shadow": {
            "br": 0,
            "color": "00000000",
            "nm": 0,
            "x": 0,
            "y": 0
        },
        "forked": true
    },
    "sknLblStrip": {
        "wType": "Label",
        "bg_type": "one",
        "border_color": "42424200",
        "border_style": "plain",
        "border_width": 0,
        "border_type": 0,
        "font_color": "4b88f100",
        "font_name": "Helvetica",
        "font_size": 70,
        "font_style": "normal",
        "font_weight": "normal",
        "background_color": "4b88f100",
        "forked": false
    },
    "sknLblTimeStamp": {
        "wType": "Label",
        "bg_type": "one",
        "border_color": "42424200",
        "border_style": "plain",
        "border_width": 0,
        "border_type": 0,
        "font_color": "8e8e8e00",
        "font_name": "Helvetica",
        "font_size": 92,
        "font_style": "normal",
        "font_weight": "normal",
        "background_color": "00000064",
        "forked": false
    },
    "sknSampleRowTemplate": {
        "wType": "FlexContainer",
        "bg_type": "one",
        "border_color": "00000000",
        "border_style": "plain",
        "border_width": 0,
        "border_type": 0,
        "background_color": "ffffff00"
    },
    "sknSampleSectionHeaderTemplate": {
        "wType": "FlexContainer",
        "bg_type": "one",
        "border_color": "00000000",
        "border_style": "plain",
        "border_width": 0,
        "border_type": 0,
        "background_color": "ffffff00"
    },
    "sknSectionHeaderLabelSkin": {
        "wType": "Label",
        "bg_type": "one",
        "border_type": 0,
        "font_color": "00000000",
        "font_name": "Helvetica",
        "font_size": 125,
        "font_style": "normal",
        "font_weight": "bold",
        "background_color": "94019464",
        "shadow": {
            "br": 0,
            "color": "00000000",
            "inner": false,
            "nm": 0,
            "x": 0,
            "y": 0
        },
        "text_shadow": {
            "br": 0,
            "color": "00000000",
            "nm": 0,
            "x": 0,
            "y": 0
        },
        "forked": true
    },
    "slDynamicNotificationForm": {
        "wType": "WatchDynamicNotificationForm",
        "bg_type": "one",
        "border_color": "ffffff00",
        "background_color": "00000000"
    },
    "slForm": {
        "wType": "Form",
        "bg_type": "one",
        "border_color": "ffffff00",
        "background_color": "ffffff00"
    },
    "slPopup": {
        "wType": "Popup",
        "bg_type": "one",
        "background_color": "7e7e7e00"
    },
    "slStaticNotificationForm": {
        "wType": "WatchStaticNotificationForm",
        "bg_type": "one",
        "background_color": "00000000"
    },
    "slTitleBar": {
        "wType": "TitleBar",
        "bg_type": "one",
        "font_color": "33333300",
        "font_name": "Helvetica",
        "font_size": 100,
        "font_weight": "normal",
        "background_color": "ffffff00"
    },
    "slWatchForm": {
        "wType": "Form",
        "bg_type": "one",
        "background_color": "00000000"
    }
}